[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "hydrotools"
description = "A code torrent of washing sprawl which in watery worlds is able of all."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
]
dynamic = ["version"]
